name: Auto Commit

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Changes
      run: |
        echo "Change made at $(date). Random number: $(( RANDOM % 100 ))" >> changes.txt

    - name: Commit Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "CodeMaestro33"  # Replace with your GitHub username
        git config user.email "achikiliakar@gmail.com"  # Replace with your GitHub email
        git add .
        git commit -m "Automated commit from GitHub Actions" || echo "No changes to commit"
        git push
