name: Auto Commit

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Generate Changes
      run: |
        echo "Change made at $(date)" >> changes.txt

    - name: Commit Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Automated commit from GitHub Actions"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
